/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: IsabelleDotJpeg (https://sketchfab.com/IsabelleDotJpeg)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-blahaj-5ac23e0cd44d49dcaaa14967f7d7a778
title: Low Poly Blåhaj
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/blahaj.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={1.3} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/blahaj.gltf')
